name = "AD_Kitaev"
uuid = "28ffd45a-d8fc-40b6-a096-198d7e880fe2"
authors = ["XingyuZhang2018 <zhangxingyu@iphy.ac.cn> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TeneT = "260a78e0-cbf2-49ba-8157-48058c700f32"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.7.1"
ArgParse = "1.1.4"
BenchmarkTools = "1.3.2"
CUDA = "=3.11.0"
ChainRulesCore = "1.15.7"
ChainRulesTestUtils = "1.10.1"
FileIO = "1.16.1"
JLD2 = "0.4.31"
KrylovKit = "=0.5.4"
LineSearches = "7.2.0"
OMEinsum = "=0.6.13"
Optim = "1.7.5"
TeneT = "0.1.0"
TimerOutputs = "0.5.23"
Zygote = "=0.6.41"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
